#!/bin/bash

ln -sf $PWD/config.bash $HOME/.bash_aliases
ls -l $HOME/.bash_aliases

ln -sf $PWD/vimrc $HOME/.vimrc
ls -l $HOME/.vimrc

ln -sf $PWD/tmux.conf $HOME/.tmux.conf
ls -l $HOME/.tmux.conf

ln -sf $PWD/neofetch.conf ~/.config/neofetch/config.conf
ls -l ~/.config/neofetch/config.conf
