#!/bin/bash

ln -sf $PWD/config.bash $HOME/.bash_aliases
ls -l $HOME/.bash_aliases

ln -sf $PWD/vimrc $HOME/.vimrc
ls -l $HOME/.vimrc

ln -sf $PWD/tmux.conf $HOME/.tmux.conf
ls -l $HOME/.tmux.conf

ln -sf $PWD/sfdx.conf $HOME/.sfdx.conf
ls -l $HOME/.sfdx.conf

