syntax on
set number " turn on line numbers
set norelativenumber " normal line numbers starting with 1 at the top …
" set ruler " ruler is the bar at the bottom and it is on by default
set wildmenu " shows command tab-completion options as a selectable menue
set showcmd
set title " shows filename in the window top bar
" set spell " spellchecking enabled by default
set lazyredraw " prevents vim from redrawing the screen after every macro execution
" tabs and indentation
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smartindent
set smarttab

" highlighting
set hlsearch " will highlight all matches :noh will turn it off
set incsearch

set linebreak
 
set history=100
filetype plugin on  " allow sensing the filetype
set formatoptions+=c
set listchars=tab:→\ ,eol:↲,nbsp:␣,space:·,trail:·,extends:⟩,precedes:⟨

set shortmess=aoOtI " avoid most 'Hit Enter …' messages
set viminfo='20,<1000,s1000

set noswapfile
set nobackup
set nowritebackup
set undodir=~/.vim/undo " sets undo directory to store undofile (below)
set undofile " activates persistent undos indipendent from session
set icon " terminal title -> filename

set scrolloff=999 " keeps cursor in the middle of the screen

" start at last place you were editing
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"au BufWritePost ~/.vimrc so ~/.vimrc

" MAPPINGS 
" CONFIG OPENING MAPPINGS
" open vimrc by entering – ev
nmap ev :e ~/repos/github/linux/dotfiles/vimrc<cr>
" open bash config by entering – eb
nmap eb :e ~/repos/github/linux/dotfiles/config.bash<cr>
" open Salesforce sfdx config by entering – es
nmap es :e ~/repos/github/linux/dotfiles/sfdx.conf<cr>
" open tmux config by entering – et
nmap et :e ~/repos/github/linux/dotfiles/tmux.conf<cr>
" VISUAL MODE KEYBINDINGS
" makes dot command work in visual mode without tying the usually needed full command
vnoremap . :norm.<CR> 
" makes visual selected lines move down one line when pressing J 
vnoremap J :m '>+1<CR>gv=gv 
" makes visual selected lines move up one line when pressing K 
vnoremap K :m '<-2<CR>gv=gv
" KEY MAPPINGS
" disable arrow keys (vi muscle memory)
noremap <up> :echoerr "Umm, use k instead"<CR>
noremap <down> :echoerr "Umm, use j instead"<CR>
noremap <left> :echoerr "Umm, use h instead"<CR>
noremap <right> :echoerr "Umm, use l instead"<CR>

" ALL AVAILABLE DEFAULT COLORSCHEMES
" blue       default    desert     evening    koehler    murphy     peachpuff  shine      torte
" darkblue   delek      elflord    industry   morning    pablo      ron        slate      zellner
" FAVOURITES: koehler, delek, peachpuff, slate, zellner
colorscheme koehler

" KEYBINDINGS
" jump back and forward through your open buffers by pressing ctrl-h and ctrl-l
map <C-H> :bprev<CR>
map <C-L> :bnext<CR>

" NEOVIM SPECIFIC CONFIGS
if has('nvim') 
  set laststatus=0 noshowmode noruler
endif
