#!/bin/sh

# sshg – ssh generate 

# gather host information via user input
read -p 'enter host alias: ' hostAlias
read -p 'enter user name: ' userName
read -p 'enter host address: ' hostAddress

# generate ssh key-pair
ssh-keygen -f ~/.ssh/"$hostAlias"_id_ed25519 -t ed25519   

# copy public key to host
ssh-copy-id -i ~/.ssh/"$hostAlias"_id_ed25519 $userName@$hostAddress -o IdentitiesOnly=yes

# add host to ssh config
echo "" >> ~/.ssh/config
echo "Host $hostAlias" >> ~/.ssh/config
echo '\t'"User $userName" >> ~/.ssh/config
echo '\t'"Hostname $hostAddress" >> ~/.ssh/config
echo '\t'"IdentityFile ~/.ssh/"$hostAlias"_id_ed25519" >> ~/.ssh/config

# connect to remote host with credentials from ssh config 
ssh $hostAlias
